---
# Installer et Configurer Jenkins sur la vm jenkins master
- name: Pré-install/config pour Jenkins Cluster
  hosts: all
  become: yes
  roles:
    - common

- name: Installer et configurer Jenkins sur la vm master
  hosts: master
  become: true
  roles:
    - jenkins


# Activer Nested Virt sur la vm Jenkins master
- name: Activer  la visrtualisation imbriqué" (Nested Virt)
  hosts: master
  become: true
  roles:
    - nested_virt


# Cloner le depot git sur la vm jenkins master



- name: Clone Jenkins lab repo on master node
  hosts: master
  become: true
  # vars:
  #   ssh_user: ubuntu
  tasks:
    - name: Ensure git is installed
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Remove the directory and its contents if present
      ansible.builtin.file:
        path: /home/{{ ssh_user }}/jenkins-lab-02
        state: absent

    - name: Recreate the directory with correct permissions
      ansible.builtin.file:
        path: /home/{{ ssh_user }}/jenkins-lab-02
        state: directory
        mode: '0755'
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"

    - name: Mark /home/hichem/jenkins-lab-02 as safe directory for Git
      command: git config --global --add safe.directory /home/{{ ssh_user }}/jenkins-lab-02
      become: true
      environment:
        HOME: /root

    - name: Clone Jenkins lab repository
      git:
        repo: https://github.com/hichemlamine28/jenkins-lab-02.git
        dest: /home/{{ ssh_user }}//jenkins-lab-02
        version: main
        force: yes
        update: yes
      become: true
      become_user: "{{ ssh_user }}"

    - name: Change ownership to jenkins:jenkins
      file:
        path: /home/{{ ssh_user }}/jenkins-lab-02
        owner: jenkins
        group: jenkins
        recurse: yes
      become: true



# Lancement de jenkins sur le navigateur chrome ou firefox

- name: Open Jenkins in local browser
  hosts: localhost
  become: false
  gather_facts: no
  vars:
    jenkins_ip: "{{ hostvars['labvm1'].ansible_host | default(hostvars['labvm1'].inventory_hostname) }}"
  tasks:
    - name: Check if Google Chrome is installed
      stat:
        path: /usr/bin/google-chrome
      register: chrome_installed

    - name: Check if Firefox is installed
      stat:
        path: /usr/bin/firefox
      register: firefox_installed

    - name: Open Jenkins in Chrome
      command: google-chrome http://{{ jenkins_ip }}:{{ jenkins_port }}
      when: chrome_installed.stat.exists
      ignore_errors: yes

    - name: Open Jenkins in Firefox (if Chrome not installed)
      command: firefox http://{{ jenkins_ip }}:{{ jenkins_port }}
      when:
        - not chrome_installed.stat.exists
        - firefox_installed.stat.exists
      ignore_errors: yes

    - name: Show message if no supported browser is found
      debug:
        msg: >-
          Aucun navigateur compatible trouvé. Veuillez installer Google Chrome ou Firefox.
          Vous pouvez ensuite accéder à Jenkins manuellement ici : http://{{ jenkins_ip }}:{{ jenkins_port }}
      when:
        - not chrome_installed.stat.exists
        - not firefox_installed.stat.exists
