---
- name: reload kvm modules
  become: true
  shell: |
    modprobe -r kvm_intel || true
    modprobe -r kvm_amd || true
    modprobe kvm_intel nested=1 || true
    modprobe kvm_amd nested=1 || true
